### ISSUE TITLE
Cards for Quick Insights

### ISSUE THREAD

**Issue by NathanHeffley** [austinkregel/nova-failed-jobs-tool#2]
Would you consider cards for some scoped insights (latest failed job details, most common failed job, scoped to a specific type of failed job, etc.) as within the scope of this package?

**Comment by austinkregel** [comment]
I'd say that it's well within the scope of the project to have more tools to keep track of failed jobs. 😄

**Comment by NathanHeffley** [comment]
I'll create a separate issue for each card I think might be useful, that way each one can get its own PR and might be less intimidating.
