### ISSUE TITLE
Add retry failed job

### ISSUE THREAD

**Issue by cbrinicombe13** [austinkregel/nova-failed-jobs-tool#27]
It would be good to have a 'Retry Job' button to use after changes have been made

**Comment by austinkregel** [comment]
Hello @cbrinicombe13!

I'm happy to report that the `Retry Job` button already exists 😄 On the failed jobs page, it's the icon in the bottom right of the job
![screenshot](https://user-images.githubusercontent.com/5355937/102728346-5e38c200-42f9-11eb-950e-2ee39ef6dcc6.png)

This one > ![screenshot](https://user-images.githubusercontent.com/5355937/102728357-6c86de00-42f9-11eb-8de8-1d31e64c7de0.jpg)
