### ISSUE TITLE
The nav item has a different name vs the page title

### ISSUE THREAD

**Issue by austinkregel** [austinkregel/nova-failed-jobs-tool#8]
The navigation item that pops up on the left side has a different name than the title of the package which pops up on the top of the page when the page loads.

**Comment by jradtilbrook** [comment]
Are you referring to the discrepancy between _Failed Job Manager_ and _Failed Jobs Log_ as shown in the image in the [readme](https://github.com/austinkregel/nova-failed-jobs-tool#a-nova-tool-to-help-debug-failed-jobs)?

**Comment by NathanHeffley** [comment]
Do you have a preference over whether `Manager` or `Log` is used?

**Comment by austinkregel** [comment]
@jradtilbrook You're correct, sorry I wasn't clearer!

And Personally, I'd want to see `Manager` and not `Log` because you can do more than just view the log here 😄

**Comment by NathanHeffley** [comment]
You're good @jradtilbrook, I just wanted to clarify it for you. I could make a PR and get credit (assuming Austin doesn't mark it as spam 😛) but I was planning on getting you get it, I've already contributed here a few times.

**Comment by jradtilbrook** [comment]
Cool, that was going to be the next question. Thanks for that!
